[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = ["packageA"]
name = "packageC"
requires-python = ">= 3.11"
version = "0.1.0"

[tool.hatch]
[tool.hatch.build]
targets.wheel.packages = [ "src/packageC" ]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
packageC = { path = ".", editable = true }
packageA = "*"

[tool.pixi.tasks]

[tool.uv]
[tool.uv.sources]
packageA = { git = "https://github.com/braniii/pixi_bug.git", rev = "packageA" }
